### ISSUE TITLE
NameError: name 'x' is not defined; Unresolved reference 'solvesolve'

### ISSUE THREAD

**Issue by jichunshen** [jerpint/rubiks_cube_convnet#1]
Hi,

When I run python3 code/cube_convnet_solver.py, it appears this error. Can you help me solve that? By the way in cube_convnet_solver.py, line 465, there is a unresolved reference 'solvesolve', can you help me solve this problem? 

Thank you!
```
Traceback (most recent call last):
  File "code/cube_convnet_solver.py", line 46, in <module>
    class Cube:
  File "code/cube_convnet_solver.py", line 77, in Cube
    for theta in (np.pi / 2, -np.pi / 2)]
  File "code/cube_convnet_solver.py", line 77, in <listcomp>
    for theta in (np.pi / 2, -np.pi / 2)]
NameError: name 'x' is not defined
```

**Comment by jerpint** [comment]
Hi @jichunshen thanks for your question.

When I originally wrote this code, it was using python2. I can confirm that I am getting the same issue you raised when using python3. I am however able to run the code succesfully using python2.  It doesn't seem obvious to me at first glance why there would be backwards incompatibility, I will investigate further.

**Comment by jerpint** [comment]
@jichunshen I've updated `master` , and am now able to run the code on both python2 and python3. Let me know if this has resolved the issues for you.

I've also included a `requirement.txt` file that i used in a virtualenv using python3

**Comment by jichunshen** [comment]
Thank you very much. I have solved that problem by conda install python.app. And run it with pythonw instead of python. I think it is because of the compatibility between matplotlib and macOS.
